################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:  # Upload config.toml
    - name: Uploads sentries config.toml
      copy:
        dest: ~/.gaiad/config/config.toml
        src: common/files/config.toml.sentry
        backup: yes

