################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

#*/2 * * * * /bin/bash -l -c ~/scripts/check-gaiad

- hosts: all
  tasks:
    - name: Setup check-gaiad cron
      cron:
        name: check-gaia
        minute: "*/2"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: /bin/bash -l -c ~/scripts/check-gaiad
        
    - name: Setup flush
      cron:
        name: flush
        minute: "*"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: /bin/bash -l -c ~/scripts/flush
