################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: Crea directorio ~/bin si no existe
      file:
        path: ~/bin
        state: directory
        mode: 0755

    - name: Subir gaiad al servidor
      copy:
        dest: ~/bin
        src:  common/files/gaiad
        backup: yes
        mode: u=rwx,g=rx,o=rx

    - name: Subir gaiacli al servidor
      copy:
        dest: ~/bin
        src:  common/files/gaiacli
        backup: yes
        mode: u=rwx,g=rx,o=rx

    - name: Crea directorio ~/.gaiad/config
      file:
        path: ~/.gaiad/config
        state: directory
        mode: 0755

    - name: Subir genesis al servidor
      copy:
        dest: ~/.gaiad/config
        src:  common/files/genesis.json
        backup: yes
        mode: u=rw,g=rw,o=r

    - name: Ejecuta gaiad version
      shell: ~/bin/gaiad version >> /tmp/ansible.log

    - name: Ejecuta gaiacli version
      shell: ~/bin/gaiacli version >> /tmp/ansible.log

