################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:  # Upload kernel tunning sysctl.conf file
    - name: Subiendo sysctl.conf
      become: yes
      copy:
        dest: /etc/sysctl.conf
        src: common/files/sysctl.conf
        backup: no
        owner: root
        mode: u=rw,g=r,o=r

    - name: Running sysctl -p to apply
      shell: "sysctl -p > /dev/null 2>&1"
      become: yes
