################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: Kill gaiad daemon
      shell: kill -9 $(pgrep gaiad)
      ignore_errors: yes
    - name: Mata tmux
      shell: tmux kill-server
      ignore_errors: yes
    - name: Kill script check_block
      shell: kill -9 $(pgrep check_block) 
      ignore_errors: yes
