################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
  - name: Modificando moniker
    lineinfile:
      name: ~/.gaiad/config/config.toml
      regexp: '^moniker ='
      line: 'moniker = "YOUR-NAME-HERE"'
