################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: Reinicia Fail2ban
      shell: service fail2ban restart 
      become: true

    - name: Comprueba servicio fail2ban
      shell: service fail2ban status >> ~/fail2ban.log
