################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: Run gaiad version and log
      shell: ~/bin/gaiad version >> /tmp/ansible.log

    - name: Run gaiacli version and log
      shell: ~/bin/gaiacli version >> /tmp/ansible.log

    - name: Ejecuta en tmux gaiad start
      shell: ~/scripts/check-gaiad

#    - name: Runs tmux gaiad start
#      shell: /bin/bash -l -c ~/scripts/check-gaiad
#      args:
#        executable: /bin/bash
