################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: DANGER!! Ejecutando gaiad unsafe-reset-all 
      shell: ~/bin/gaiad unsafe-reset-all >> ~/gaiad.log
