################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
- import_playbook: kill-gaiad.yml
- import_playbook: update-gaia.yml
- import_playbook: unsafe-reset-all.yml
- import_playbook: upload-genesis.yml
- import_playbook: run-gaia.yml
