################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:  # Elegir entre uno de los 2 metodos y borrar el otro
    - name: Solo Subir fichero al servidor
      copy:
        dest: ~/scripts/
        src: ../scripts/peers-moniker
        mode: u=rwx,g=rx,o=rx

#    - name: Solo extraer files.tgz into user home
#      unarchive:
#        src: ./files.tgz
#        dest: ~/
