#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################
# Comando:
# gaiacli keys add <nombreWallet>
#
echo "¿Qué nombre quieres ponerle a la wallet?"
read -r name

gaiacli keys add "${name}"
