#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################

#Used variables

chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
keyname=`gaiacli keys list | awk 'FNR==2{print $1}'`


#
# Read title 
#

echo "Write a title for your proposal:"
read title


#
# Read description 
#

echo "Write the description of your proposal:"
read description

#
# Read type
#
echo "What type is your proposal (text/software_upgrade/parameter_change)?:"
read type

#
# Read deposit
#
echo "What deposit would you like to use for your proposal?"
read deposit

#
# Read gas price
#
echo "What gas price you want to apply?"
read gasprice


#
# Read Wallet password
#

echo "Wallet password:"
read -s password

  echo "Submitting the proposal:"
  echo "gaiacli tx gov submit-proposal --title $title --description $description --type $type --deposit=${deposit}muon  --gas auto --gas-adjustment 1.5 --gas-prices ${gasprice}muon --from=${keyname} --chain-id=$chain_id"
	gaiacli tx gov submit-proposal --title $title --description $description --type $type --deposit=${deposit}muon --gas auto --gas-adjustment 1.5 --gas-prices ${gasprice}muon --from=${keyname} --chain-id=$chain_id

 
echo "done"
