#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#                                              #
################################################
# Script para ver los validadores
#
# Comando:
# gaiacli query tendermint-validator-set --trust-node=true
#
gaiacli query tendermint-validator-set --trust-node=true