################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
- import_playbook: install-packages.yml
- import_playbook: update-firewall-valid.yml
- import_playbook: kernel-tunning.yml
- import_playbook: max-open-files.yml
- import_playbook: nagios-setup.yml
- import_playbook: deploy-gaia.yml
- import_playbook: upload-scripts.yml
- import_playbook: kill-gaiad.yml
- import_playbook: modify-config-toml-valid.yml
- import_playbook: run-gaia.yml
- import_playbook: cron-setup-valid.yml
