################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
  - name: Set ulimit values
    become: yes
    blockinfile:
      name: /etc/security/limits.conf
      block: |
        user    hard    nofile    500000
        user    soft    nofile    450000
    
