################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
  - name: Modificando seeds
    lineinfile:
      name: ~/.gaiad/config/config.toml
      regexp: '^seeds ='
      line: 'seeds = "ba3bacc714817218562f743178228f23678b2873@public-seed-node.cosmoshub.certus.one:26656, 89e4b72625c0a13d6f62e3cd9d40bfc444cbfa77@34.65.6.52:26656, 3028c6ee9be21f0d34be3e97a59b093e15ec0658@91.205.173.168:26656, 1d741cfee5d78c5caf0b5a5b513e7793d50ea26f@goku.forbole.com:26656"'

  - name: Modificando persistent_peers  
    lineinfile:
      name: ~/.gaiad/config/config.toml
      regexp: '^persistent_peers ='
      line: 'persistent_peers = "[AQUI TUS SENTRIES]"'
  
  - name: Modificando private peers  
    lineinfile:
      name: ~/.gaiad/config/config.toml
      regexp: '^private_peer_ids ='
      line: 'private_peer_ids = "[AQUI TUS VALIDADORES Y SENTRIES PRIVADOS]"'

  - name: Modificando pex=true  
    lineinfile:
      name: ~/.gaiad/config/config.toml
      regexp: '^pex ='
      line: 'pex = true'

  - name: Modificando addr_book_strict
    lineinfile:
      name: ~/.gaiad/config/config.toml
      regexp: '^addr_book_strict ='
      line: 'addr_book_strict = false'
