################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: Subir script al servidor
      copy:
        dest: /etc/rc.local
        src: common/files/rc.local.sentry
        backup: yes
        mode: u=rwx,g=rx,o=rx
      become: yes

    - name: Ejecuta script subido
      shell: /etc/rc.local >> /tmp/script.log
      become: yes
