################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:  # Upload genesis
    - name: Subir genesis al servidor
      copy:
        dest: ~/.gaiad/config
        src:  common/files/genesis.json
        backup: yes
        mode: u=rw,g=rw,o=r
