################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: Subir script al servidor
      copy:
        dest: ~/scripts/
        src: ../scripts/check_block
        mode: u=rwx,g=rx,o=rx

    - name: Kill previous proccess
      shell: pkill check_block
      ignore_errors: yes

    - name: Running script in background
      shell: nohup ~/scripts/check_block </dev/null >/dev/null 2>&1 &
