################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

- hosts: all
  tasks:
    - name: Crea directorio ~/bin si no existe
      file:
        path: ~/bin
        state: directory
        mode: 0755
    - name: Subir gaiad al servidor
      copy:
        dest: ~/bin
        src:  common/files/gaiad
        backup: no
        mode: u=rwx,g=rx,o=rx

    - name: Subir gaiacli al servidor
      copy:
        dest: ~/bin
        src:  common/files/gaiacli
        backup: no
        mode: u=rwx,g=rx,o=rx

    - name: Ejecuta comando gaiad version
      shell: ~/bin/gaiad version >> ~/gaiad.log

    - name: Ejecuta comando gaiacli version
      shell: ~/bin/gaiacli version >> ~/gaiad.log

