{
 "title": "Cosmos Network",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "query": "label_values(network)" },
   { "name": "hostname", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peers{hostname=\"[[hostname]]\",job=\"[[network]]-[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Tiempo de bloque",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{hostname=\"[[hostname]]\",job=\"[[network]]-[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Last Block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_height{hostname=\"[[hostname]]\",job=\"[[network]]-[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block time Short Slow",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_consensus_block_interval_seconds{hostname=\"[[hostname]]\",job=\"[[network]]-[[hostname]]\",network=\"[[network]]\"}[10m])/rate(tendermint_consensus_block_interval_seconds{hostname=\"[[hostname]]\",job=\"[[network]]-[[hostname]]\",network=\"[[network]]\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HD Free Space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "Gigabytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",mountpoint=\"/data\",network=\"[[network]]\"}\n",
     "legendFormat": "{{hostname}} {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_free_bytes{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",mountpoint=\"/\",network=\"[[network]]\"}\n",
     "legendFormat": "{{hostname}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} load 1m"
    },
    {
     "expr": "node_load5{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} load 5m"
    },
    {
     "expr": "node_load15{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "{{hostname}} load 15m"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "node_load1{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "[[hostname]] Load av 1m"
    },
    {
     "expr": "node_load5{hostname=\"[[hostname]]\",job=\"node_[[hostname]]\",network=\"[[network]]\"}",
     "legendFormat": "[[hostname]] Load av 5m"
    }
   ]
  }
 ]
}