#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################
# Shows current block height
while :
do
	clear
	echo ""
	echo "Actual Block Height of your node"
	curl -s http://localhost:26657/status | jq '.result.sync_info.latest_block_height'
	echo ""
	echo ""
	sleep 5
done
