#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

keyname=`gaiacli keys list | awk 'FNR==2{print $1}'`
chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
pubkey=`gaiad tendermint show-validator`

echo "Recuerda que este script usa muon como moneda, si no es asi debes cambiarlo"
echo ""
echo "¿Cual es tu pgp de Keybase?"
read pgp
echo ""
echo "¿Qué quieres poner en detalles"
read details
echo ""
echo "¿Qué cantidad?"
read amount
echo ""
echo "¿Cual es la contraseña?"
read -s password
echo ""
echo "${password}" | gaiacli tx staking create-validator --commission-max-change-rate=0.10 --commission-max-rate=1 --commission-rate=1 --moniker=${keyname} --min-self-delegation=1 --identity=${pgp} --from=${keyname} --details=${details} --chain-id=${chain_id} --pubkey=${pubkey} --amount=${amount}muon
