#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #
#                                              #
################################################

curl -s http://localhost:26657/net_info|grep -E '\"id\":|\"listen_addr":'|sed 's/"id": "//g'|sed 's/",//g'|sed 's/"listen_addr": "/@/g'|sed 's/^[ \t]*//g'|sed ':a;N;$!ba;s/\n@/@/g'


