#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################

account_cosmos=`gaiacli keys list -o=json | jq -r '.[].address'`

echo "account_cosmos = $account_cosmos"

