#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################
# Shows account_cosmosval

keyname=`gaiacli keys list --output=json | jq -r '.[].name'`
cosmosvaloper=`gaiacli keys show ${keyname} --bech=val --output=json | jq -r '.address'`
echo $cosmosvaloper