#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################

account_cosmos=`gaiacli keys list | awk 'FNR==2{print $3}'`

echo "account_cosmos = $account_cosmos"

