#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################
# Shows account_cosmosval

keyname=`gaiacli keys list | awk 'FNR==2{print $1}'`
cosmosvaloper=`gaiacli keys show ${keyname} --bech=val | awk 'FNR==2{print $3}'`
