#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################
# Shows balance

chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`

account_cosmos=`gaiacli keys list -o=json | jq -r '.[].address'`

gaiacli query account $account_cosmos --chain-id=$chain_id --trust-node=true --output=json | jq

