#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################
# Nagios check for Cosmos sentrys and validators
#
# |'label'=value[UOM];[warn];[crit];[min];[max]
# |'peers'=$connected_peers;3;2;0;40

connected_peers=`curl -s http://localhost:26657/net_info | jq '.result.n_peers' | tr -d \" `
case $connected_peers in
[10-50]*)
echo "OK - $connected_peers peers connected |'peers'=$connected_peers"
exit 0
;;
[3-9]*)
echo "WARNING - $connected_peers peers connected |'peers'=$connected_peers"
exit 1
;;
[0-2]*)
echo "CRITICAL - $connected_peers peers connected |'peers'=$connected_peers"
exit 2
;;
*)
echo "UNKNOWN - $connected_peers peers connected |'peers'=$connected_peers"
exit 3
;;
esac

