#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################
#
# go version go1.11.5 linux/amd64
#
mkdir -p $GOPATH/src/github.com/cosmos
cd $GOPATH/src/github.com/cosmos
git clone https://github.com/cosmos/cosmos-sdk
git fetch --tags
cd cosmos-sdk && git checkout master
make tools install
clear
echo ""
gaiad version --long
gaiacli version --long
