#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #                              
#                                              #
################################################
# Shows cosmovaloper

keyname=`gaiacli keys list -o=json | jq -r '.[].name'`
cosmovaloper=`gaiacli keys show ${keyname} --bech=val --output=json | jq -r '.address'`

echo "cosmovaloper = $cosmovaloper"

