#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#                                              #
################################################
# Is my validator jailed? 

keyname=`gaiacli keys list -o=json | jq -r '.[].name'`
chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
cosmosvaloper=`gaiacli keys show ${keyname} --bech=val --output=json | jq -r '.address'`

gaiacli query staking validator $cosmosvaloper --chain-id=$chain_id --output=json | jq '.jailed'
