#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#                                              #
################################################
# Is my validator jailed? 

keyname=`gaiacli keys list | awk 'FNR==2{print $1}'`
chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`
cosmosvaloper=`gaiacli keys show ${keyname} --bech=val | awk 'FNR==2{print $3}'`

gaiacli query staking validator $cosmosvaloper --chain-id=$chain_id --output=json | jq '.jailed'
