#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#                                              #
################################################
# Shows the number of peers we are connected to
#
clear
echo ""
echo "Actually connected to..."
curl -s http://localhost:26657/net_info | jq '.result.n_peers'
echo "peers"
echo ""

curl -s http://localhost:26657/net_info | jq '.result.peers[].node_info.moniker'
