#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #                              
#                                              #
################################################
# Comando:
# gaiacli query account <wallet> --trust-node=true
#
gaiacli keys list

echo  "¿Qué wallet quieres usar?"
read -r wallet

gaiacli query account "${wallet}" --trust-node=true
