#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #
#                                              #
################################################
# Comando:
# gaiacli keys add --recover <nombreWallet>
#

echo "¿Qué nombre quieres ponerle a la wallet?"
read -r name

gaiacli keys add --recover "$name"