#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @4llfr33d0m:matrix.org         #
#                                              #
################################################
# Script para la instalacion de lo necesario para un nodo de Cosmos:
#
sudo apt update && sudo apt -y upgrade
sudo apt install -y make wget curl git gcc jq build-essential
wget -c 'https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz' -O go1.11.5.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.11.5.linux-amd64.tar.gz
sudo rm -Rf go1.11.5.linux-amd64.tar.gz

cat <<EOT >> ~/.profile
#Go:
PATH="\$PATH:/usr/local/go/bin"
GOPATH="\$HOME/go"
PATH="\$PATH:\$GOROOT/bin:\$GOPATH/bin"
EOT

source /home/$USER/.profile

mkdir -p $GOPATH/src/github.com/cosmos && cd $GOPATH/src/github.com/cosmos
git clone https://github.com/cosmos/cosmos-sdk && cd cosmos-sdk/
git checkout master
make tools install