#!/bin/bash
################################################
#                                              #
#  Made with love in Colm3naSVQ by :           #
#                                              #
#  @wimel85(wiπΞl)->@cosmaut:matrix.org        #
#  @DerFredy -> @derfredy:matrix.org           #
#                                              #
################################################
# Script para redelegar fondos
#
# Comando:
# gaiacli tx staking redelegate \
#   --addr-validator-source=<account_cosmosval> \
#   --addr-validator-dest=<account_cosmosval> \
#   --shares-fraction=50 \
#   --from=<key_name> \
#   --chain-id=<chain_id>
#
# Variables:
#
chain_id=$(curl -s http://localhost:26657/status | jq -r '.result.node_info.network')

gaiacli keys list

echo "¿Qué wallet quieres usar?(cosmos123...)"
read -r wallet

echo "¿De qué validador quieres desvincularte?(cosmosvaloper...)"
read -r oldvalid

echo "¿A qué validador quieres vincularte?(cosmosvaloper...)"
read -r newvalid

echo "¿Qué cantidad quieres vincular?"
read -r amount

gaiacli tx staking redelegate "${oldvalid}" "${newvalid}" "${amount}" --from="${wallet}" --chain-id="${chain_id}" --fees=5000uatom -y
